### PR TITLE
Overhaul

### PR DESCRIPTION
**Pull request by ichthyosaurus**
- completely overhauled the user interface
- added the GPL where necessary
- added support for automated database schema upgrades
- changed the database layout (database updates itself)
    - added support for time zones
    - added field for possible future feature: audio notes
    - changed internal date format from "dd.MM.yyyy | hh:mm" to (standard) "yyyy-MM-dd hh:mm:ss"
    - save seconds
    - renamed 'favorites' to 'bookmarks' (an important entry is not necessarily my favorite)
- added a new cover page
- simplified reloading, improving performance (changes no longer require a full reload)
- added new mood "not okay": "okay" is slightly positive, "not okay" is slightly negative; there is no "neutral" mood (database updates itself)
- refactored export features
    - made exports translatable
    - added new export options: plain markdown and markdown for pandoc
- updated the German translation to use polite "Sie"
- replaced app icon by new, more "sailfishy" variant
- implemented quickly changing the mood of an entry in the overview list
- implemented searching for entries between two dates

### CODE REVIEW

**Comment by AlphaX2** [comment]
Oh my god! What a huge contribution, thats crazy. Did you leave at least one file in it's orignal condition? 😄 

I just found minnor details: first some Nemo.Configuration imports should be kicked out and - no offense - I do not really like the "lorem ipsum" background. It's a little to much. Could we go back to a less intense variant? And maybe there should be a option to choose the loose german language version. I mean it's my personal diary, not a buisness partner, isn't it? 😉

But I really love this much cleaner code and the optimized structure so much. And there some parts I've learned new things. Thats fantastic.

 Thank you very much.

**Comment by ichthyosaurus** [comment]
> Oh my god! What a huge contribution, thats crazy. Did you leave at least one file in it's orignal condition? :smile: 

No, I don't think so :laughing: 

> I just found minnor details: first some Nemo.Configuration imports should be kicked out

done

> and - no offense - I do not really like the "lorem ipsum" background. It's a little to much. Could we go back to a less intense variant?

You're right! I simplified it again and now I'm quite fond of it :smile: . What do you think?

> And maybe there should be a option to choose the loose german language version. I mean it's my personal diary, not a buisness partner, isn't it? :wink:

I see your point, but I don't see an easy way to make it configurable. My train of thought was: "It's an app, a tool, and not my friend. So it shouldn't talk as if it were." I like that more, but you can change it, of course!

> But I really love this much cleaner code and the optimized structure so much. And there some parts I've learned new things. That's fantastic.
> 
> Thank you very much.

Thanks :). Glad you like it. I rewrote almost your entire app and was a bit afraid if you're happy with that :wink: .

**Comment by ichthyosaurus** [comment]
> I see your point, but I don't see an easy way to make it configurable. My train of thought was: "It's an app, a tool, and not my friend. So it shouldn't talk as if it were." I like that more, but you can change it, of course!

(I already thought about adding de_DE and de_CH as separate translations, but Sailfish doesn't support de_CH.)

**Comment by AlphaX2** [comment]
Hey again and sorry!

I had no spare time to check all your changes in the last days, so I did today. I've found a bug in EntryElement:83 preventing the deletion of entries. This change works:

`entryList.remorseDelete(deleteEntry(realModel, index, rowid))`

Also FirstPage seems buggy, if there are no entries (fresh start or all deleted), because the placeholder never shows up. It seems the relating signals are never fired, but I'm not sure why.

Thank you very much for your support.

**EDIT:** maybe we should add any function to set the protection code usage back to 0/false (configuration value), if the app is uninstalled, otherwise it will ask for your code after reinstall. But that could be a long(er) time ago? Maybe it should depend if the database in place or not.

**Comment by ichthyosaurus** [comment]
No reason to apologize!

I'm very busy this week and will look at it in more detail next weekend. 

---

> entryList.remorseDelete(deleteEntry(realModel, index, rowid))

Are you sure this doesn't delete the entry already _before_ using the remorse thing?

---

Placeholder: that's weird. In harbour-captains-log.qml:207, the model is initially loaded when the Python module is ready. At line 132 loadingFinished() is called. Is it possible that loadingFinished() is called before the FirstPage component is completed, thus before the connections are ready at line 35?

This might work:
- property bool appWindow.initialLoadingDone: false
- in loadModel(): initialLoadingDone = true
- and FirstPage.qml:87 as `enabled: !appWindow.initialLoadingDone` -> this binding will (and should be) broken when the model is reloaded and the connections (onLoadingFinished) are used.

---

I don't know how we can detect if the app is being removed...

**Comment by ichthyosaurus** [comment]
> I don't know how we can detect if the app is being removed...

I've opened an issue for that. I think that's so complicated it should be done separately from this PR.

**Comment by ichthyosaurus** [comment]
(updated the first comment with most important changes)

**Comment by ichthyosaurus** [comment]
Would it be ok for you if I publish my changes as a fork/beta/preview/... on OpenRepos?

(+ updated the first comment with most important changes)

**Comment by AlphaX2** [comment]
Yes you can. My Sailfish device died and I lost my 2-factor authentification app too, so I was not able to enter GitHub. But I found my restore-keys now. I'm so heavily loaded with work in the next few weeks, I can't check/work on the app.

If you want, you could also send the rpm file for uploading in my repo?

**Comment by ichthyosaurus** [comment]
Oh, that's unfortunate; hope you can get things back to normal again!

I published it here: https://openrepos.net/content/ichthyosaurus/captains-log-updated

I updated the entry text, here it is:

```
<p>This is an updated version of <a href="https://openrepos.net/content/alphax2/captains-log">this app</a>. I rewrote the user interface and introduced new features (see changelog). This is the only update in my repository; upcoming releases will again be in AlphaX2's repo.</p>

<p>Captain's Log is a simple diary application for keeping track of your thoughts.</p>

<p>Features:</p>

<ul>
	<li>lockscreen to restrict access</li>
	<li>bookmark entries</li>
	<li>add hashtags</li>
	<li>browse your entries by different filters</li>
	<li>export your data to different file formats</li>
</ul>

<p><strong>Note:</strong> Captain's Log can hide your entries behind a protection code but it's nothing special. Your data is neither encrypted nor otherwise protected against a bad guy with physical access to your device.</p>

<p>Captain's Log is written in pure Python and QML. It is free software released under the GNU GPL v3+. The source code is available here: <a href="https://github.com/AlphaX2/Captains-Log-Sailfish/pull/2">https://github.com/AlphaX2/Captains-Log-Sailfish</a></p>

<p>(All texts used in the screenshots are random quotes from "<a href="https://en.wikipedia.org/wiki/Walden">Walden</a>" by H. D. Thoreau.)</p>
```

I attached ~the RPM,~ my database for testing and screenshots, plus the screenshot files. If you have time again, you can take everything and update your repository with it.

[logbook.tar.gz](https://github.com/AlphaX2/Captains-Log-Sailfish/files/4798376/logbook.tar.gz)
[screenshots.tar.gz](https://github.com/AlphaX2/Captains-Log-Sailfish/files/4798378/screenshots.tar.gz)

Edit: removed the now outdated RPM; current one is on Openrepos
Edit 2: updated link to Openrepos page
Edit 3: updated the description

**Pull request merged**
